= Tuesmon Documentation
:toc: left
:numbered:


[[introduction]]
Introduction
------------

Free. Open Source. Powerful. _Tuesmon_ is a project management platform for startups
and agile developers & designers who want a simple, beautiful tool that makes work
truly enjoyable.


[[how-it-works]]
How it Works
------------

_Tuesmon_ is made up of two components: link:https://github.com/tuesmoncom/tuesmon-front[tuesmon-front]
and link:https://github.com/tuesmoncom/tuesmon-back[tuesmon-back]

- *tuesmon-front* has the frontend related code built with *angularjs* and *coffeescript*.
  It can run on any static file server like nginx.
- *tuesmon-back* has the backend related code consisting of an API, built using *django*
  and *python3*.

_Tuesmon_ has some other modules, but they are optional and documented in other sections.


[[requirements]]
Requirements
------------

This is a list of major _Tuesmon_ dependencies:

Runtime:

- Python >= 3.4
- PostgreSQL >= 9.4
- RabbitMQ (optional as long as you don't want async notifications)

Compile time:

- GCC & Development Headers
- Ruby >= 2.1 (only for compiling sass)
- NodeJS >= 7.0 (with npm and gulp for downloading dependencies and compiling coffeescript)

Hardware

- The main Tuesmon hardware restriction is having **at least 0.75 GB of RAM**. When installing
the python requirements, the package lxml will use gcc to build itself and fail if there
is not enough memory.
- Tuesmon code doesn't need a lot of disc space. Only the database or the media directory might need
more space with the passage of time.


[[installation-guide]]
Installation Guide
------------------

This section details everything you need to know to get _Tuesmon_ up and running
in both development and production environments.

=== Setup Production Environment

link:setup-production.html[This document contains the complete, step by step tutorial] of how
to properly setup _Tuesmon_ for a low traffic production environment.

=== Setup Development Environment

You can view the complete documentation on how to link:setup-development.html[setup a proper
development environment].

=== Other Ways to Setup an Initial Environment

In addition to the traditional step-by-step manuals, _Tuesmon_ comes with a
collection of provisioning scripts and Vagrant support, and
link:setup-alternatives.html[complete documentation of how to use them].

=== Setup FAQs and common Bugs

You can view a list of common FAQs and bugs related to the setup process link:setup-faqs.html[FAQs
and common bugs].

=== Upgrades

Instructions on link:upgrades.html[how to upgrade your Tuesmon instance].


[[how-to-contribute]]
How to Contribute
-----------------

Because _Tuesmon_ is an open source project, we gratefully accept contributions in various forms.

Examples of contributions include:

- link:#reporting-bugs[Bug reports]
- Code patches
- Improvements
- Patch reviews
- link:#translate[Translate]
- link:#themes[Create a theme]
- link:#contrib-plugins[Code contrib plugins]

Before starting to develop a big feature (intended to be included on the _Tuesmon_ code base), it is
strongly recommended that you reach out to us on the link:http://groups.google.com/d/forum/tuesmoncom[mailing list].


[[reporting-bugs]]
Reporting Bugs
~~~~~~~~~~~~~~

Before reporting a bug or requesting a new feature, please consider these general points:

- Check that someone hasn't already filed the bug or feature request by searching, or running custom
  queries in, the link:https://manage.tuesmon.com/project/tuesmon/issues[issue tracker].
- Check the right repository to use for reporting an issue: bugs related to UI should go to *tuesmon-front*,
  but if something is broken on the backend, an issue should be opened on the *tuesmon-back* repository.
- Ask on the link:http://groups.google.com/d/forum/tuesmoncom[mailing list] first if you're not sure if
  what you're seeing is a bug.
- Don't use the GitHub issues system to ask support questions. Use the
  link:http://groups.google.com/d/forum/tuesmoncom[mailing list] for that.
- Don’t use GitHub issues for lengthy discussions, because they're likely to get lost. If a particular
  ticket is controversial, please move the discussion to the
  link:http://groups.google.com/d/forum/tuesmoncom[mailing list].


[[api]]
API
---
_Tuesmon_ has a complete REST API (the one used by the web app), check the full API
documentation link:api.html[here].


[[webhooks]]
Webhooks
--------
_Tuesmon_ has a webhooks notification system, check the full documentation link:webhooks.html[here].


[[contrib-plugins]]
Contrib Plugins
---------------

Tuesmon supports the inclusion of contrib plugins, each plugin has its own
documentation and repository. The currently supported plugins are:

* link:http://github.com/tuesmoncom/tuesmon-contrib-github-auth[tuesmon-github-auth]: GitHub Auth plugin
* link:http://github.com/tuesmoncom/tuesmon-contrib-hipchat[tuesmon-contrib-hipchat]: HipChat integration plugin
* link:http://github.com/tuesmoncom/tuesmon-contrib-letschat[tuesmon-contrib-letschat]: Lets Chat integration plugin
* link:http://github.com/tuesmoncom/tuesmon-contrib-slack[tuesmon-contrib-slack]: Slack integration plugin


[[themes]]
Themes
-------

You can create custom themes in Tuesmon.

To create a theme you have to create a new folder in `/app/themes/` with your theme name, or duplicate a
 previous one. If you create a new folder, then create two files inside.

* `variables.scss` - to override sass variables, fonts, mixins helpers..etc.

* `custom.scss` - to override any defined Tuesmon style for any module or layout.

Remember, the file `variables.scss` should only contain sass declarations that do not generate code by
 themselves (like variables or mixins).

If you need to override a style and generate some new CSS, you should do it in `custom.scss`.

Please, check the default Tuesmon theme to understand how these files work properly.

When the files are created you have to run gulp with the theme name. This is the same as `gulp default` but
 uses your theme instead of the default tuesmon theme.

[source]
----
gulp --theme themeName
----

If you want to compile all themes you should run.

[source]
----
gulp compile-themes
----


[[community]]
Community
---------

link:http://groups.google.com/d/forum/tuesmoncom[Tuesmon has a mailing list]. Feel free to join it
and ask any questions you may have.

To subscribe for announcements of releases, important changes and so on, please follow
link:https://twitter.com/tuesmoncom[@tuesmoncom] on Twitter or read our link:https://blog.tuesmon.com[blog].


[[donations]]
Donations
---------

We are grateful for your emails volunteering donations to _Tuesmon_. We feel comfortable accepting them under
these conditions: the first is that we will only do so while we are in the current beta/pre-revenue stage,
and the second is that whatever money is donated will go towards a bounty fund. Starting Q2 2015 we will be
engaging much more actively with our community to help further the development of Tuesmon, and we will use
these donations to reward people working alongside us.

If you wish to make a donation to this Tuesmon fund, you can do so via link:http://www.paypal.com[PayPal]
using the email: eposner@tuesmon.com


[[license]]
License
-------

Every code patch accepted in the Tuesmon codebase is accepted under the AGPL v3.0 license. It is important
that you do not include any code which cannot be licensed under AGPL v3.0.

You can see the complete license in the `LICENSE` file in the root of the repository.
