= Tuesmon: Other ways to setup initial environment
:toc: left
:numbered:

[[setup-tuesmon-scripts]]
Setup using **tuesmon-scripts**
-----------------------------

Introduction
~~~~~~~~~~~~

**tuesmon-scripts** primarily follows the standard installation process, but makes it more automatic. If
something goes wrong in the process, you should try to fix it by following the manual deploy process.

**tuesmon-scripts** always installs a specific (the most recent) version of Tuesmon (tuesmon-front and tuesmon-back)


Important notes about **tuesmon-scripts**
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

- In an alpha state, and has not been heavily tested in different environments.
- Designed to work with tuesmon-vagrant (see next section of this documentation).
- Does not support reprovisioning (updating) at this moment, that is still in development.
- Does not support installation with root user.
- The installation is not 100% ready for production.


Requirements
~~~~~~~~~~~~

- Freshly installed and updated Ubuntu 16.04
- Bash shell
- Git


Setup server-like environment
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Make sure you have a fresh and updated Ubuntu 16.04 machine or virtual image:

[source, txt]
----
$ git clone https://github.com/tuesmoncom/tuesmon-scripts.git
$ cd tuesmon-scripts
$ bash setup-server.sh
----


Setup development-like environment
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

This setup is much like the previous one but with a few differences:

- It does not install services like nginx, as they are only necessary for production
- It sets all hostnames to localhost to easily run everything on localhost

Make sure you have a fresh and updated Ubuntu 16.04 machine or virtual image:

[source, txt]
----
$ git clone https://github.com/tuesmoncom/tuesmon-scripts.git
$ cd tuesmon-scripts
$ bash setup-devel.sh
----

[[setup-tuesmon-vagrant]]
Setup using **tuesmon-vagrant**
-----------------------------

Introduction
~~~~~~~~~~~~

**tuesmon-vagrant** offers a Vagrantfile which makes it easy to turn on a fully provisioned
virtual machine. **tuesmon-vagrant** uses **tuesmon-scripts** for its provisioning scripts.


Important notes about using **tuesmon-vagrant**
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

- The installation is not 100% ready for production, it is designed for use as a demonstration.
- Does not support reprovisioning at this moment.

Dependencies
~~~~~~~~~~~~

- link:https://www.virtualbox.org/wiki/Downloads[VirtualBox]
- link:http://downloads.vagrantup.com/[Vagrant]


Installation
~~~~~~~~~~~~

[source, bash]
----
git clone https://github.com/tuesmoncom/tuesmon-vagrant.git
cd tuesmon-vagrant
vagrant plugin install vagrant-vbguest
vagrant up
----

After installing, the Tuesmon service should be up and running. You can access it by going
to http://localhost:8000 with your browser.

You can use the following credentials to login to the recently created Tuesmon instance:

- Username: `admin`
- Password: `123123`

You can access the machine using ssh, if you would like to make some tweaks:

[source, bash]
----
vagrant ssh
----

[[setup-tuesmon-docker]]
Setup using **tuesmon-docker**
-----------------------------


Important notes about using **tuesmon-docker**
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Docker is not officially supported by the Tuesmon development team but a link:https://github.com/ipedrazas/tuesmon-docker[docker script]
has been developed by link:https://github.com/ipedrazas[Iván Pedrazas], and
link:https://github.com/benhutchins/docker-tuesmon[another docker script]
has been developed by link:https://github.com/benhutchins[Benjamin Hutchins].

[[setup-tuesmon-puppet]]
Setup using **puppet-tuesmon**
----------------------------


Important notes about using **puppet-tuesmon**
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Puppet is not officially supported by the Tuesmon development team but a link:https://github.com/opus-codium/puppet-tuesmon[puppet module]
has been developed by the link:https://github.com/orgs/opus-codium/people[Opus-Codium folks].

[[setup-tuesmon-cloudron]]
Setup using **tuesmon-cloudron**
------------------------------


Important notes about using **tuesmon-cloudron**
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

`Tuesmon` is available as a 1-click install on link:https://cloudron.io[Cloudron]. This is not
officially supported by the Tuesmon development team but is maintained by the Cloudron team at
their link:https://git.cloudron.io/cloudron/tuesmon-app[tuesmon package repo].

[caption="Install",link=https://cloudron.io/button.html?app=io.tuesmon.cloudronapp]
image::https://cloudron.io/img/button.svg[Install]

